# app.py – Streamlit entry point for the Model Equality Testing suite

"""Multi‑page Streamlit application.

* The main page (this file) provides a short introduction and lets the user
  upload a pickled data file containing the model samples.
* Individual tests live in the ``pages/`` directory – one page per test.

To run the app locally:
```
streamlit run app.py
```
"""

import streamlit as st
import pickle
from pathlib import Path

st.set_page_config(page_title="Model Equality Testing", layout="centered")

st.title("Model Equality Testing")
st.markdown(
    """
    This application lets you run a variety of statistical tests that compare
    language‑model output distributions.  Upload a ``.pkl`` file that contains a
    dictionary with the keys ``'samples'`` (model → ``CompletionSample``) and
    ``'prompt_map'`` (prompt → id).

    The sidebar will list the available tests – each test appears as a separate
    page under the *Pages* section.
    """
)

# ---------- Upload data ----------
uploaded = st.file_uploader(
    "Upload the ``my_llm_data.pkl`` file (generated by the notebooks)",
    type=["pkl"],
    help="The pickle should contain a dict with keys 'samples' and 'prompt_map'.",
)

if uploaded is not None:
    # Load the pickle into session state so that page scripts can reuse it.
    try:
        data = pickle.load(uploaded)
        if not isinstance(data, dict) or "samples" not in data:
            st.error("Invalid pickle format – expected a dict with a 'samples' key.")
        else:
            st.session_state["loaded_data"] = data
            st.success("Data loaded successfully!")
            st.write(f"Available models: {list(data['samples'].keys())}")
    except Exception as e:
        st.error(f"Failed to load pickle: {e}")
else:
    st.info("Upload a data file to enable the test pages.")

st.sidebar.markdown("---")
st.sidebar.markdown("**Note:** The actual tests are available under the *Pages* navigation on the left.")
