"""
Semantic axis interpretation layer for model equality testing.

This module provides tools to interpret distributional differences between LLM outputs
using semantic axes derived from pole corpora. After quantum metrics detect that two
models differ (e.g., trace distance = 0.23), semantic axes explain *what* differs
(e.g., "professionalism +0.54, g=0.82, p<0.001").

Semantic axes are constructed from pairs of pole corpora (e.g., professionalism.jsonl
and casualness.jsonl generated by the semantic-pole project). Each axis is a unit
vector in SBERT embedding space pointing from the negative pole centroid to the
positive pole centroid.

Key design principles:
- Semantic axes are an **interpretation layer only** — they don't replace PCA or
  quantum metrics
- Reuses the same SBERT embeddings that quantum metrics already compute
- L2 normalization ensures cosine-similarity semantics throughout
- Statistical methodology: Welch's t-test, Hedges' g, Benjamini-Hochberg FDR correction
"""

import json
import logging
import numpy as np
import os
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Tuple
from scipy import stats

from model_equality_testing.distribution import CompletionSample
from .embeddings import EmbeddingModel


@dataclass
class SemanticAxis:
    """A semantic axis in embedding space.

    Attributes:
        name: Axis identifier (e.g., "professionalism-casualness")
        negative_pole: Negative pole name (e.g., "professionalism")
        positive_pole: Positive pole name (e.g., "casualness")
        axis_vector: Unit vector pointing from negative to positive pole (d,)
        negative_centroid: Mean of L2-normalized negative pole embeddings (d,)
        positive_centroid: Mean of L2-normalized positive pole embeddings (d,)
        embedding_model: Model used for embedding (e.g., "all-mpnet-base-v2")
        embedding_dim: Dimension of embeddings
        pole_distance: ||positive_centroid - negative_centroid|| before normalization
        metadata: Provenance and quality metrics (see load_axis_from_jsonl)
    """
    name: str
    negative_pole: str
    positive_pole: str
    axis_vector: np.ndarray
    negative_centroid: np.ndarray
    positive_centroid: np.ndarray
    embedding_model: str
    embedding_dim: int
    pole_distance: float
    metadata: dict

    def __post_init__(self):
        """Validate axis after construction."""
        # Check dimensions match
        if self.axis_vector.shape[0] != self.embedding_dim:
            raise ValueError(
                f"axis_vector dimension ({self.axis_vector.shape[0]}) != "
                f"embedding_dim ({self.embedding_dim})"
            )
        if self.negative_centroid.shape[0] != self.embedding_dim:
            raise ValueError(
                f"negative_centroid dimension ({self.negative_centroid.shape[0]}) != "
                f"embedding_dim ({self.embedding_dim})"
            )
        if self.positive_centroid.shape[0] != self.embedding_dim:
            raise ValueError(
                f"positive_centroid dimension ({self.positive_centroid.shape[0]}) != "
                f"embedding_dim ({self.embedding_dim})"
            )

        # Check axis vector is unit norm
        norm = np.linalg.norm(self.axis_vector)
        if not np.isclose(norm, 1.0, atol=1e-5):
            raise ValueError(
                f"axis_vector must be unit norm, got norm={norm:.6f}"
            )

        # Check poles separate
        if self.pole_distance < 1e-6:
            raise ValueError(
                f"Poles don't separate (pole_distance={self.pole_distance:.2e} < 1e-6). "
                f"Check that pole corpora represent distinct concepts."
            )

    def __repr__(self) -> str:
        """Compact representation without dumping 768-dim arrays."""
        sep_ratio = self.metadata.get('separation_ratio', None)
        if sep_ratio is not None:
            return (
                f"SemanticAxis(name='{self.name}', "
                f"negative='{self.negative_pole}', "
                f"positive='{self.positive_pole}', "
                f"dim={self.embedding_dim}, "
                f"pole_distance={self.pole_distance:.3f}, "
                f"separation_ratio={sep_ratio:.2f})"
            )
        else:
            return (
                f"SemanticAxis(name='{self.name}', "
                f"negative='{self.negative_pole}', "
                f"positive='{self.positive_pole}', "
                f"dim={self.embedding_dim}, "
                f"pole_distance={self.pole_distance:.3f})"
            )


@dataclass
class AxisProjectionResult:
    """Per-axis comparison result between two samples.

    Attributes:
        axis_name: Name of the axis
        negative_pole: Negative pole name (for display)
        positive_pole: Positive pole name (for display)
        mean_a: Mean projection score for sample A
        mean_b: Mean projection score for sample B
        std_a: Standard deviation for sample A
        std_b: Standard deviation for sample B
        sem_a: Standard error of the mean for sample A
        sem_b: Standard error of the mean for sample B
        delta: mean_a - mean_b
        hedges_g: Hedges' g bias-corrected effect size
        t_pvalue: Welch's t-test p-value (no equal-variance assumption)
        corrected_pvalue: FDR-corrected p-value
        wasserstein: 1D Wasserstein distance between distributions
        n_a: Sample size A
        n_b: Sample size B
    """
    axis_name: str
    negative_pole: str
    positive_pole: str
    mean_a: float
    mean_b: float
    std_a: float
    std_b: float
    sem_a: float
    sem_b: float
    delta: float
    hedges_g: float
    t_pvalue: float
    corrected_pvalue: float
    wasserstein: float
    n_a: int
    n_b: int


@dataclass
class SemanticInterpretation:
    """Collection of per-axis comparison results.

    Attributes:
        results: List of per-axis results
        embedding_model: Model used for embeddings
        label_a: Label for sample A (e.g., "fp32", "Model A")
        label_b: Label for sample B (e.g., "int8", "Model B")
    """
    results: List[AxisProjectionResult]
    embedding_model: str
    label_a: str
    label_b: str

    def sorted_by_effect(self) -> List[AxisProjectionResult]:
        """Return results sorted by |hedges_g| descending."""
        return sorted(self.results, key=lambda r: abs(r.hedges_g), reverse=True)

    def summary(self, top_k: int = 5) -> str:
        """Generate human-readable summary of semantic differences.

        Args:
            top_k: Number of top axes to include

        Returns:
            Formatted summary string
        """
        sorted_results = self.sorted_by_effect()[:top_k]

        lines = [
            f"Semantic Interpretation ({len(sorted_results)} axes, sorted by effect size):",
            ""
        ]

        for r in sorted_results:
            # Format p-value
            if r.corrected_pvalue < 0.001:
                p_str = "p < 0.001"
            elif r.corrected_pvalue < 0.01:
                p_str = f"p = {r.corrected_pvalue:.3f}"
            else:
                p_str = f"p = {r.corrected_pvalue:.2f}"

            # Significance marker
            sig_marker = " *" if r.corrected_pvalue < 0.05 else ""

            # Axis line
            lines.append(
                f"  {r.negative_pole} ← → {r.positive_pole}:  "
                f"Δ = {r.delta:+.2f}  g = {r.hedges_g:.2f}  {p_str}{sig_marker}"
            )

            # Direction explanation
            if r.corrected_pvalue < 0.05:
                if r.delta > 0:
                    direction = f"{self.label_a} is more toward {r.positive_pole} than {self.label_b}"
                else:
                    direction = f"{self.label_a} is more toward {r.negative_pole} than {self.label_b}"
                lines.append(f"    {direction}")
            else:
                lines.append(f"    No significant difference (p > 0.05 after FDR correction)")

            lines.append("")

        if any(r.corrected_pvalue < 0.05 for r in sorted_results):
            lines.append("  * significant after Benjamini-Hochberg correction (α = 0.05)")

        return "\n".join(lines)


def _load_jsonl_texts(path: str) -> Tuple[List[str], str]:
    """Load texts from a JSONL file.

    Args:
        path: Path to JSONL file

    Returns:
        (texts, pole_name) tuple

    Raises:
        FileNotFoundError: If path doesn't exist
        ValueError: If all texts are empty after filtering
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"JSONL file not found: {path}")

    texts = []
    pole_name = None

    with open(path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            record = json.loads(line)
            text = record.get('text', '').strip()

            # Extract pole name from first record's metadata
            if i == 0 and pole_name is None:
                metadata = record.get('metadata', {})
                if 'concept' in metadata:
                    pole_name = metadata['concept']

            if text:  # Filter empty texts
                texts.append(text)

    # Fall back to filename-derived pole name
    if pole_name is None:
        filename = Path(path).stem
        pole_name = filename
        logging.info(
            f"No metadata.concept found in {path}, using filename-derived pole name: {pole_name}"
        )

    if len(texts) == 0:
        raise ValueError(f"No valid texts found in {path} after filtering empty strings")

    return texts, pole_name


def load_axis_from_jsonl(
    negative_pole_path: str,
    positive_pole_path: str,
    axis_name: str,
    embedding_model: str = "all-mpnet-base-v2",
    batch_size: int = 32
) -> SemanticAxis:
    """Load a semantic axis from pole corpus JSONL files.

    Args:
        negative_pole_path: Path to negative pole JSONL (e.g., professionalism.jsonl)
        positive_pole_path: Path to positive pole JSONL (e.g., casualness.jsonl)
        axis_name: Name for this axis (e.g., "professionalism-casualness")
        embedding_model: SBERT model name (default: "all-mpnet-base-v2")
        batch_size: Batch size for embedding

    Returns:
        SemanticAxis object

    Raises:
        FileNotFoundError: If either JSONL file doesn't exist
        ValueError: If poles don't separate or all texts are empty
    """
    # Load texts from both poles
    neg_texts, neg_name = _load_jsonl_texts(negative_pole_path)
    pos_texts, pos_name = _load_jsonl_texts(positive_pole_path)

    # Warn on small corpora
    if len(neg_texts) < 50:
        logging.warning(
            f"Negative pole corpus has only {len(neg_texts)} samples (< 50). "
            f"Axis quality may be poor."
        )
    if len(pos_texts) < 50:
        logging.warning(
            f"Positive pole corpus has only {len(pos_texts)} samples (< 50). "
            f"Axis quality may be poor."
        )

    # Embed texts
    embedder = EmbeddingModel(embedding_model, model_type="sbert")
    logging.info(f"Embedding {len(neg_texts)} negative pole texts...")
    neg_embeddings = embedder.encode(neg_texts, batch_size=batch_size, show_progress_bar=True)
    logging.info(f"Embedding {len(pos_texts)} positive pole texts...")
    pos_embeddings = embedder.encode(pos_texts, batch_size=batch_size, show_progress_bar=True)

    # L2-normalize embeddings before computing centroids
    neg_embeddings = neg_embeddings / np.linalg.norm(neg_embeddings, axis=1, keepdims=True)
    pos_embeddings = pos_embeddings / np.linalg.norm(pos_embeddings, axis=1, keepdims=True)

    # Compute centroids
    neg_centroid = np.mean(neg_embeddings, axis=0)
    pos_centroid = np.mean(pos_embeddings, axis=0)

    # Compute intra-pole RMS standard deviation
    neg_intra_std = np.sqrt(np.mean(np.sum((neg_embeddings - neg_centroid)**2, axis=1)))
    pos_intra_std = np.sqrt(np.mean(np.sum((pos_embeddings - pos_centroid)**2, axis=1)))

    # Compute pole distance and axis vector
    diff = pos_centroid - neg_centroid
    pole_distance = np.linalg.norm(diff)

    if pole_distance < 1e-6:
        raise ValueError(
            f"Poles don't separate (distance={pole_distance:.2e}). "
            f"The two pole corpora may represent the same concept."
        )

    axis_vector = diff / pole_distance

    # Compute separation ratio
    mean_intra_std = (neg_intra_std + pos_intra_std) / 2
    separation_ratio = pole_distance / max(mean_intra_std, 1e-10)

    if separation_ratio < 1.0:
        logging.warning(
            f"Separation ratio is {separation_ratio:.2f} < 1.0. "
            f"Poles overlap substantially; axis may have poor discriminating power."
        )

    # Build metadata
    metadata = {
        "negative_pole_path": str(Path(negative_pole_path).absolute()),
        "positive_pole_path": str(Path(positive_pole_path).absolute()),
        "negative_pole_samples": len(neg_texts),
        "positive_pole_samples": len(pos_texts),
        "negative_pole_intra_std": float(neg_intra_std),
        "positive_pole_intra_std": float(pos_intra_std),
        "separation_ratio": float(separation_ratio),
        "created_at": datetime.utcnow().isoformat() + "Z",
    }

    return SemanticAxis(
        name=axis_name,
        negative_pole=neg_name,
        positive_pole=pos_name,
        axis_vector=axis_vector,
        negative_centroid=neg_centroid,
        positive_centroid=pos_centroid,
        embedding_model=embedding_model,
        embedding_dim=embedder.embedding_dim,
        pole_distance=float(pole_distance),
        metadata=metadata,
    )


def _sanitize_filename(name: str) -> str:
    """Sanitize axis name for use as filename.

    Replaces characters not in [a-zA-Z0-9_-] with underscore.

    Args:
        name: Axis name

    Returns:
        Sanitized filename-safe name
    """
    return re.sub(r'[^a-zA-Z0-9_-]', '_', name)


def save_axis(axis: SemanticAxis, path: str):
    """Save a semantic axis to an .npz file.

    Args:
        axis: SemanticAxis to save
        path: Output path (.npz)
    """
    # Prepare metadata JSON
    metadata_dict = {
        "name": axis.name,
        "negative_pole": axis.negative_pole,
        "positive_pole": axis.positive_pole,
        "embedding_model": axis.embedding_model,
        "embedding_dim": axis.embedding_dim,
        "pole_distance": axis.pole_distance,
        "metadata": axis.metadata,
    }
    metadata_json = json.dumps(metadata_dict)

    # Save to npz
    np.savez_compressed(
        path,
        version=np.array([1], dtype=np.int32),
        axis_vector=axis.axis_vector,
        negative_centroid=axis.negative_centroid,
        positive_centroid=axis.positive_centroid,
        metadata_json=np.array([metadata_json], dtype=object),
    )
    logging.info(f"Saved axis '{axis.name}' to {path}")


def load_axis(path: str) -> SemanticAxis:
    """Load a semantic axis from an .npz file.

    Args:
        path: Path to .npz file

    Returns:
        SemanticAxis object

    Raises:
        FileNotFoundError: If path doesn't exist
        ValueError: If version is unsupported
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"Axis file not found: {path}")

    data = np.load(path, allow_pickle=True)

    # Check version
    version = int(data['version'][0])
    if version != 1:
        raise ValueError(
            f"Unsupported axis file version: {version}. "
            f"This code supports version 1 only."
        )

    # Load metadata
    metadata_json = str(data['metadata_json'][0])
    metadata_dict = json.loads(metadata_json)

    axis = SemanticAxis(
        name=metadata_dict['name'],
        negative_pole=metadata_dict['negative_pole'],
        positive_pole=metadata_dict['positive_pole'],
        axis_vector=data['axis_vector'],
        negative_centroid=data['negative_centroid'],
        positive_centroid=data['positive_centroid'],
        embedding_model=metadata_dict['embedding_model'],
        embedding_dim=metadata_dict['embedding_dim'],
        pole_distance=metadata_dict['pole_distance'],
        metadata=metadata_dict['metadata'],
    )

    logging.info(f"Loaded axis '{axis.name}' from {path}")
    return axis


def save_axes(axes: List[SemanticAxis], directory: str):
    """Save multiple axes to a directory (one .npz file per axis).

    Args:
        axes: List of SemanticAxis objects
        directory: Output directory

    Raises:
        ValueError: If axis names are not unique
    """
    # Check for duplicate names
    names = [axis.name for axis in axes]
    if len(names) != len(set(names)):
        duplicates = [name for name in names if names.count(name) > 1]
        raise ValueError(
            f"Duplicate axis names found: {set(duplicates)}. "
            f"All axis names must be unique."
        )

    # Create directory if needed
    os.makedirs(directory, exist_ok=True)

    # Save each axis
    for axis in axes:
        sanitized_name = _sanitize_filename(axis.name)
        path = os.path.join(directory, f"{sanitized_name}.npz")
        save_axis(axis, path)


def load_axes(directory: str) -> List[SemanticAxis]:
    """Load all axes from a directory.

    Args:
        directory: Directory containing .npz axis files

    Returns:
        List of SemanticAxis objects, sorted alphabetically by filename

    Raises:
        FileNotFoundError: If directory doesn't exist
    """
    if not os.path.isdir(directory):
        raise FileNotFoundError(f"Directory not found: {directory}")

    # Find all .npz files, sorted alphabetically
    npz_files = sorted([
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.endswith('.npz')
    ])

    if len(npz_files) == 0:
        logging.warning(f"No .npz files found in {directory}")
        return []

    # Load each axis
    axes = []
    for path in npz_files:
        axes.append(load_axis(path))

    return axes


def project_onto_axis(embeddings: np.ndarray, axis: SemanticAxis) -> np.ndarray:
    """Project embeddings onto a semantic axis.

    Args:
        embeddings: Embeddings array (N, d)
        axis: SemanticAxis

    Returns:
        Projection scores (N,). Positive = toward positive_pole.

    Raises:
        ValueError: If embedding dimension doesn't match axis dimension
    """
    if embeddings.shape[1] != axis.embedding_dim:
        raise ValueError(
            f"Embedding dimension ({embeddings.shape[1]}) != "
            f"axis dimension ({axis.embedding_dim})"
        )

    # L2-normalize embeddings for consistency with axis construction
    normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

    # Project onto axis
    scores = normalized @ axis.axis_vector

    return scores


def project_onto_axes(embeddings: np.ndarray, axes: List[SemanticAxis]) -> np.ndarray:
    """Project embeddings onto multiple axes.

    Args:
        embeddings: Embeddings array (N, d)
        axes: List of SemanticAxis objects

    Returns:
        Projection scores (N, K) where K = len(axes)

    Raises:
        ValueError: If embedding dimensions don't match
    """
    if len(axes) == 0:
        raise ValueError("axes list is empty")

    # Check all axes have the same dimension
    dims = [axis.embedding_dim for axis in axes]
    if len(set(dims)) > 1:
        raise ValueError(
            f"Axes have different dimensions: {set(dims)}. "
            f"All axes must use the same embedding model."
        )

    if embeddings.shape[1] != dims[0]:
        raise ValueError(
            f"Embedding dimension ({embeddings.shape[1]}) != "
            f"axis dimension ({dims[0]})"
        )

    # L2-normalize embeddings
    normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

    # Stack axis vectors and project in one matmul
    axis_matrix = np.vstack([axis.axis_vector for axis in axes])  # (K, d)
    scores = normalized @ axis_matrix.T  # (N, K)

    return scores


def _benjamini_hochberg(pvalues: np.ndarray) -> np.ndarray:
    """Apply Benjamini-Hochberg FDR correction to p-values.

    Args:
        pvalues: Array of p-values

    Returns:
        FDR-corrected p-values
    """
    pvalues = np.asarray(pvalues, dtype=float)
    n = len(pvalues)

    if n <= 1:
        return pvalues.copy()

    # Sort p-values and compute correction
    sorted_indices = np.argsort(pvalues)
    sorted_pvalues = pvalues[sorted_indices]
    corrected = sorted_pvalues * n / np.arange(1, n + 1)

    # Enforce monotonicity (corrected p-values should be non-decreasing)
    corrected = np.minimum.accumulate(corrected[::-1])[::-1]

    # Cap at 1.0
    corrected = np.minimum(corrected, 1.0)

    # Un-sort back to original order
    result = np.empty(n)
    result[sorted_indices] = corrected

    return result


def interpret_difference(
    embeddings_a: np.ndarray,
    embeddings_b: np.ndarray,
    axes: List[SemanticAxis],
    label_a: str = "Sample A",
    label_b: str = "Sample B"
) -> SemanticInterpretation:
    """Interpret semantic differences between two samples.

    Args:
        embeddings_a: Embeddings for sample A (N_a, d)
        embeddings_b: Embeddings for sample B (N_b, d)
        axes: List of semantic axes
        label_a: Label for sample A (e.g., "fp32")
        label_b: Label for sample B (e.g., "int8")

    Returns:
        SemanticInterpretation with per-axis results
    """
    if len(axes) == 0:
        raise ValueError("axes list is empty")

    # Project onto all axes
    proj_a = project_onto_axes(embeddings_a, axes)  # (N_a, K)
    proj_b = project_onto_axes(embeddings_b, axes)  # (N_b, K)

    results = []
    pvalues = []

    for i, axis in enumerate(axes):
        scores_a = proj_a[:, i]
        scores_b = proj_b[:, i]

        n_a = len(scores_a)
        n_b = len(scores_b)

        # Compute statistics
        mean_a = np.mean(scores_a)
        mean_b = np.mean(scores_b)
        std_a = np.std(scores_a, ddof=1)
        std_b = np.std(scores_b, ddof=1)
        sem_a = std_a / np.sqrt(n_a)
        sem_b = std_b / np.sqrt(n_b)
        delta = mean_a - mean_b

        # Hedges' g with guards
        s_avg = np.sqrt((std_a**2 + std_b**2) / 2)
        if s_avg < 1e-10:
            d = 0.0
        else:
            d = delta / s_avg

        if n_a + n_b < 4:
            J = 1.0
        else:
            J = 1 - 3 / (4 * (n_a + n_b) - 9)

        hedges_g = d * J

        # Welch's t-test
        t_result = stats.ttest_ind(scores_a, scores_b, equal_var=False)
        t_pvalue = t_result.pvalue
        pvalues.append(t_pvalue)

        # Wasserstein distance
        wasserstein = stats.wasserstein_distance(scores_a, scores_b)

        results.append(AxisProjectionResult(
            axis_name=axis.name,
            negative_pole=axis.negative_pole,
            positive_pole=axis.positive_pole,
            mean_a=float(mean_a),
            mean_b=float(mean_b),
            std_a=float(std_a),
            std_b=float(std_b),
            sem_a=float(sem_a),
            sem_b=float(sem_b),
            delta=float(delta),
            hedges_g=float(hedges_g),
            t_pvalue=float(t_pvalue),
            corrected_pvalue=0.0,  # Will be filled in after FDR correction
            wasserstein=float(wasserstein),
            n_a=n_a,
            n_b=n_b,
        ))

    # Apply BH-FDR correction
    corrected_pvalues = _benjamini_hochberg(np.array(pvalues))
    for i, result in enumerate(results):
        result.corrected_pvalue = float(corrected_pvalues[i])

    return SemanticInterpretation(
        results=results,
        embedding_model=axes[0].embedding_model,
        label_a=label_a,
        label_b=label_b,
    )


def interpret_samples(
    sample_a: CompletionSample,
    sample_b: CompletionSample,
    axes: List[SemanticAxis],
    label_a: str = "Sample A",
    label_b: str = "Sample B",
    embedding_model: str = None,
    _precomputed_embeddings: tuple = None
) -> SemanticInterpretation:
    """Interpret semantic differences between CompletionSamples.

    Convenience wrapper that embeds CompletionSamples and calls interpret_difference().

    Args:
        sample_a: CompletionSample A
        sample_b: CompletionSample B
        axes: List of semantic axes
        label_a: Label for sample A
        label_b: Label for sample B
        embedding_model: Model to use for embedding (default: use axis model)
        _precomputed_embeddings: Optional (emb_a, emb_b) tuple to skip embedding

    Returns:
        SemanticInterpretation
    """
    if len(axes) == 0:
        raise ValueError("axes list is empty")

    # Use precomputed embeddings if provided
    if _precomputed_embeddings is not None:
        emb_a, emb_b = _precomputed_embeddings
    else:
        # Import here to avoid circular dependency
        from .embeddings import embed_sample

        # Use axis model if not specified
        if embedding_model is None:
            embedding_model = axes[0].embedding_model

        # Warn if model mismatch
        axis_models = set(axis.embedding_model for axis in axes)
        if len(axis_models) > 1:
            logging.warning(
                f"Axes use different embedding models: {axis_models}. "
                f"This may produce inconsistent results."
            )
        if embedding_model != axes[0].embedding_model:
            logging.warning(
                f"Embedding model '{embedding_model}' != axis model '{axes[0].embedding_model}'. "
                f"Results may be unreliable."
            )

        # Embed samples
        emb_a = embed_sample(sample_a, model_name=embedding_model)
        emb_b = embed_sample(sample_b, model_name=embedding_model)

    return interpret_difference(emb_a, emb_b, axes, label_a, label_b)


def axis_correlations(axes: List[SemanticAxis]) -> np.ndarray:
    """Compute cosine similarity matrix between axis vectors.

    Args:
        axes: List of semantic axes

    Returns:
        Correlation matrix (K, K) where K = len(axes)

    Warns:
        If any pair of axes correlates above 0.7
    """
    if len(axes) == 0:
        raise ValueError("axes list is empty")

    # Stack axis vectors
    axis_matrix = np.vstack([axis.axis_vector for axis in axes])  # (K, d)

    # Compute cosine similarities (axis vectors are already unit norm)
    corr_matrix = axis_matrix @ axis_matrix.T  # (K, K)

    # Check for high correlations (excluding diagonal)
    K = len(axes)
    for i in range(K):
        for j in range(i + 1, K):
            corr = corr_matrix[i, j]
            if abs(corr) > 0.7:
                logging.warning(
                    f"High correlation ({corr:.2f}) between axes "
                    f"'{axes[i].name}' and '{axes[j].name}'. "
                    f"These dimensions may overlap; interpretation may overcount differences."
                )

    return corr_matrix
